name: Alvin Ord's - Evening Rotation (10 PM)

on:
  schedule:
    # Run at 10:00 PM Central Time (4:00 AM UTC next day)
    - cron: '0 4 * * *'
  workflow_dispatch: # Allow manual triggering for testing

jobs:
  evening-rotation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Run evening rotation
        env:
          HYPERZOD_API_KEY: ${{ secrets.HYPERZOD_API_KEY }}
          HYPERZOD_TENANT_ID: ${{ secrets.HYPERZOD_TENANT_ID }}
          ALVIN_ORDS_MERCHANT_ID: ${{ secrets.ALVIN_ORDS_MERCHANT_ID }}
        run: |
          node alvin-ords-automation.js
